
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
